services:
  db01:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-docker/db01:/var/lib/postgresql/data  # Local directory for database storage
      - ./postgres-docker/postgresql.conf:/etc/postgresql/postgresql.conf  # Custom config outside data dir
      - ./postgres-docker/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgres-docker/init.sql:/docker-entrypoint-initdb.d/init.sql  # One-time init script
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - rideshare-net
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]  # Tell Postgres where to find config

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin  # Persist pgAdmin settings
    depends_on:
      - db01
    networks:
      - rideshare-net

networks:
  rideshare-net:
    driver: bridge
