services:
  db01:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  # Named volume for database persistence
      - ./postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - rideshare-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Named volume for pgAdmin persistence
    depends_on:
      - db01
    networks:
      - rideshare-net

networks:
  rideshare-net:

volumes:
  postgres_data:
  pgadmin_data:
