services:
  db01:
    image: postgres:16.1
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-docker/db01:/var/lib/postgresql
      - /var/run/postgresql:/var/run/postgresql
      - .postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # literally accept any connection yolo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - rideshare-net
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db01
    networks:
      - rideshare-net

networks:
  rideshare-net:
    driver: bridge
